name: Deploy Lambda to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1  # Sostituiscilo con la tua regione AWS

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Images
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          
          # Definiamo le cartelle delle Lambda
          for dir in lambda/*; do
            if [ -d "$dir" ]; then
              LAMBDA_NAME=$(basename "$dir")
              IMAGE_TAG="${ECR_REGISTRY}/${LAMBDA_NAME}:latest"

              echo "Building and pushing $LAMBDA_NAME..."
              docker build -t $IMAGE_TAG $dir
              docker push $IMAGE_TAG
            fi
          done
